owner: ealsuite
repo: status

sites:
  - name: EalSuite
    url: https://www.ealsuite.com
    maxResponseTime: 5000
  - name: Documentation Website
    url: https://ealsuite.com/documentation
    maxResponseTime: 5000    

status-website:
  cname: status.ealsuite.com  
  logoUrl: https://raw.githubusercontent.com/ealsuite/status/master/assets/Ealsuite_Logo.png
  favicon: https://raw.githubusercontent.com/ealsuite/status/master/assets/apple-touch-icon.png
  name: EalSuite Status
  introTitle: "About this site"
  introMessage: Welcome to EalSuite's real-time and historical data on system performance.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
